
blueprint:
  name: Matter – 2-Button Switch (single/double/long met loop tot release)
  description: >
    Voor Matter event-entiteiten (bijv. LIFX 2-Button). Single/double voeren direct acties uit.
    Long press voert een herhaal-actie uit met instelbaar interval en limiet, tot release.
    Velden met * zijn verplicht.
  domain: automation
  source_url: https://github.com/timmstek/HA_Buttons_Switches/blob/main/blueprints/automation/tim_stek/ButtonsSwitches_Matter.yaml

  input:
    # ---------- Algemeen ----------
    loop_interval_ms:
      name: Loop-interval (ms) *
      description: Interval tussen iteraties tijdens LONG press
      default: 200
      selector:
        number:
          min: 50
          max: 2000
          step: 50
          unit_of_measurement: ms
          mode: slider

    loop_max_iterations:
      name: Max. iteraties per LONG press *
      description: Veiligheidslimiet; voorkomt oneindige loop
      default: 60
      selector:
        number:
          min: 1
          max: 500
          step: 1
          mode: box

    # ---------- Matter event-entiteiten ----------
    button1_entity:
      name: Button 1 event entity *
      description: Event-entiteit voor knop 1 (bv. event.devicename_button_31)
      selector:
        entity:
          domain: event

    button2_entity:
      name: Button 2 event entity *
      description: Event-entiteit voor knop 2 (bv. event.devicename_button_32)
      selector:
        entity:
          domain: event

    # ---------- Acties per knop ----------
    b1_single_action:
      name: Button 1 – Single press (actie)
      default: []
      selector: { action: {} }

    b1_double_action:
      name: Button 1 – Double press (actie)
      default: []
      selector: { action: {} }

    b1_long_loop_action:
      name: Button 1 – Long press (LOOP-actie per iteratie)
      description: Wordt bij elke loop-iteratie uitgevoerd tot release of limiet
      default: []
      selector: { action: {} }

    b2_single_action:
      name: Button 2 – Single press (actie)
      default: []
      selector: { action: {} }

    b2_double_action:
      name: Button 2 – Double press (actie)
      default: []
      selector: { action: {} }

    b2_long_loop_action:
      name: Button 2 – Long press (LOOP-actie per iteratie)
      description: Wordt bij elke loop-iteratie uitgevoerd tot release of limiet
      default: []
      selector: { action: {} }

mode: single
max_exceeded: silent

# -- TRIGGERS --
trigger:
  - platform: state
    id: matter_button_state
    entity_id: !input button1_entity
  - platform: state
    id: matter_button_state
    entity_id: !input button2_entity

# -- VARIABELEN --
variables:
  loop_interval_ms: !input loop_interval_ms
  loop_max: !input loop_max_iterations

  # Welke entiteit en press-type (uit attribute event_type)?
  matter_btn_entity: "{{ trigger.entity_id | default('') }}"
  matter_event_type: "{{ state_attr(matter_btn_entity, 'event_type') | default('') }}"
  matter_button_name: >-
    {% if 'button_31' in matter_btn_entity or 'button_1_matter' in matter_btn_entity or 'button_1' in matter_btn_entity or 'switch_1' in matter_btn_entity %}
      button_1
    {% elif 'button_32' in matter_btn_entity or 'button_2_matter' in matter_btn_entity or 'button_2' in matter_btn_entity or 'switch_2' in matter_btn_entity %}
      button_2
    {% else %}
      unknown
    {% endif %}

# -- ACTIES --
action:
  - choose:
      # Button 1
      - conditions: "{{ matter_button_name == 'button_1' and matter_event_type == 'multi_press_1' }}"
        sequence: !input b1_single_action
      - conditions: "{{ matter_button_name == 'button_1' and matter_event_type == 'multi_press_2' }}"
        sequence: !input b1_double_action
      - conditions: "{{ matter_button_name == 'button_1' and matter_event_type == 'long_press' }}"
        sequence:
          - repeat:
              sequence:
                - sequence: !input b1_long_loop_action
                - wait_template: "{{ state_attr(matter_btn_entity, 'event_type') != 'long_press' }}"
                  timeout:
                    milliseconds: !input loop_interval_ms
                  continue_on_timeout: true
              until:
                - condition: template
                  value_template: >
                    {{ state_attr(matter_btn_entity, 'event_type') != 'long_press'
                       or repeat.index >= loop_max }}

      # Button 2
      - conditions: "{{ matter_button_name == 'button_2' and matter_event_type == 'multi_press_1' }}"
        sequence: !input b2_single_action
      - conditions: "{{ matter_button_name == 'button_2' and matter_event_type == 'multi_press_2' }}"
        sequence: !input b2_double_action
      - conditions: "{{ matter_button_name == 'button_2' and matter_event_type == 'long_press' }}"
        sequence:
          - repeat:
              sequence:
                - sequence: !input b2_long_loop_action
                - wait_template: "{{ state_attr(matter_btn_entity, 'event_type') != 'long_press' }}"
                  timeout:
                    milliseconds: !input loop_interval_ms
                  continue_on_timeout: true
              until:
                - condition: template
                  value_template: >
                    {{ state_attr(matter_btn_entity, 'event_type') != 'long_press'
                       or repeat.index >= loop_max }}
    default: []
